README.md

Update to the clone url since we changed the structure of having 1 repo to 3 separate ones(ios, android, web).

update clone url

---

frontend/src/components/Tabs/index.js
frontend/src/containers/Collection/index.js
frontend/src/index.css

I created a simple Tabs component, which allows the user to filter the collection views by location.
- The tab system was designed to be used with Hooks. I left a comment on the usage I imagined while designing the component.
- The "All" tab is hard coded, while the other tabs are created using a `map()` function on `props.locations`.
- The "notch" on the active button is done with CSS, using pseudoclasses.
- The buttons are based on `<a>` elements.
- When a user clicks a tab, the `onClick()` event calls `props.setState(index)`, which is the Hook's setState function passed as a prop to the Tabs component.
- The tabs change classes depending on the provided Tab state. If the Tab state equals the Tab index, its `className = "tab-active"`. Otherwise, its 'className = "tab-inactive"`

Created Location Tabs for Collection Views

---

.env.example
.eslintrc
.huskyrc.json
package.json
src/App.js
src/components/nav/index.js
src/components/nav/styles.js
src/constants/Color.js
src/index.js
src/pages/Home.js
src/routes/index.js
src/serviceWorker.js
src/styles/index.js

**What does this PR do?**
- Setup Eslint with Husky to lint on pre-commit
**Description of Task to be completed?**
- Extends the create-react-app Eslint with airbnb configs (must include the ```EXTEND_ESLINT``` env variable in local ```.env``` file to work, we can remove the extending configs if anything)
- Adds separate linting tasks as npm scripts
- Create a pre hook that will lint files in src folder before committing (currently does every file in the folder including ones that aren't staged yet)
**How should this be manually tested?**
- Attempt to commit files that don't pass the linter
**Pull Request Type (check one)**
**Screenshots (if appropriate)**
None

Eslint + Husky Setup

---

package.json
src/components/Container.js
src/components/nav/index.js
src/components/nav/styles.js
src/components/ui/GetInvolved.js
src/pages/Home.js
src/pages/Petitions.js
src/routes/index.js
yarn.lock

- Created the petitions page with a placeholder text.
- Created the route for the petitions page.
- Created the link for the petitions page in the nav.
- Edited the styles in the nav to accommodate new links.
- Fixed linting errors in `/src/components/Container.js` and other relevant files (mostly with `--fix`) - needs particular review there since I didn't write that component - this is where `PropTypes` came in - will remove if there's a better solution.
- Create `PetitionLink` components (or equivalent)
- Fetch data from API resolving the petitions - follow up with backend team to see how this will be done
- Styles, populate the page, etc.
- No testing yet
- https://trello.com/c/An6ydzbd/48-petition-page

feat: set up petitions page, route, and styles, fix: lint errors

---

src/components/footer/index.js
src/components/footer/style.js

- add the footer of the pages
- 
-no testing yet
-
-  [x] Feature

feature:footer

---

.huskyrc.json
package.json

closes #18 
- Fixes husky lint issue
- Configured husky to lint code before committing code
- run git commit -m 'your message'
- Husky fix

Chore husky fix

---

src/components/profileDetails/PersonProfile.js
src/routes/index.js

- activates the Donation button
- create onClick event listener on the donation button
- onClick redirect to the donations page with the id
- run npm start
- Click on a person profile
- Click on the Donations button
- You should redirect to donations page with the user Id
- Activate Donation Button on PersonProfile

activates donation button

---

src/components/ui/media/Media.js
src/components/ui/mediaList/MediaList.js

- fixes rendering of media cards
- set media card to render a loading card while links are loading
- npm start
- Click on a person 
- Fix Media Component

fixed media component

---

src/components/profileDetails/PersonProfile.js
src/components/ui/profileList/ProfileList.js
src/components/ui/profilePreview/ProfilePreview.js
src/pages/Donations.js
src/routes/index.js

- Fix API Routes 
- Change getting the profile by id to getting the profile by identifier
- Visit the homepage and navigate to a profile detail
- https://trello.com/c/gHgXdlTr/85-fix-api-routes

Fix API Routes 

---

src/components/ui/petition/Petition.js
src/components/ui/petition/styles.js
src/pages/Donations.js
src/pages/Petitions.js
src/routes/index.js

- Fill the donations and petitions page with content from API
- Create components and styles for this to be accomplished
- Prepare the links to go to the details page
- Use production data
- None yet
- https://trello.com/c/xwKJHqmx/49-donation-page
- https://trello.com/c/An6ydzbd/48-petition-page

feat: petitions page, donations page, route, components for each

---

src/pages/notFound/NotFound.js
src/pages/notFound/style.js
src/routes/index.js

- Fix eslint errors 
-Clean up errors on the development branch
-
-

fixed ESLint errors

---

src/components/common/ErrorBoundry.js
src/components/ui/petition/Petition.js
src/components/ui/petition/styles.js
src/components/ui/profilePreview/styles.js
src/pages/Donations.js
src/pages/Home.js
src/pages/Petitions.js
src/pages/notFound/NotFound.js
src/pages/notFound/style.js
src/routes/index.js

- UI cleanup
- Fix width on mobile
- Fix some styling to match design
- Visit the application
-

UI cleanup

---

src/components/profileDetails/PersonProfile.js

This PR changes the title of the Context section to Their Story.
Matching the FIGMA Web MVP for Context title.
By opening up the Profile Detail page,

change title from context to their story in profileDetail

---

src/components/footer/Footer.test.js

-  Fix Footer Test Suite
- Footer fixes from a previous PR break for the footer test suite. Fixed the typo to match the naming: https://github.com/Say-Their-Name/say-their-names-web/pull/57
- Run ``` Yarn run test:all``` and check if all tests pass
- n/a

chore: fix typo in footer test

---

src/components/ui/petition/styles.js

- Properly resizing image for each donation and petition
-
- Navigate to the donation page and petition page
- https://trello.com/c/2boV2rbi/105-properly-resize-petition-image
**Donation Before**
**Donation After**

properly resize petition image

---

src/pages/Donations.js
yarn.lock

- Re-orders No Donations Found message
- Taken out unnecessary spaces
- Added 'S' to 'DONATION'
- Routing needs a new issue created
-
-

Issue 74 donations

---

.eslintrc
.prettierrc
package.json
yarn.lock

- Add prettier to unify the formatting of the codebase
- Align the codebase to the same formatting
- N/A
- https://trello.com/c/ghJHwn0D/109-add-prettier

Chore: Add prettier

---

.github/workflows/unit-test.yaml

-  Adds Github Action to run unit tests when a new PR is made to development or master
- n/a
- Create a new pull request when this merged
- Click on the actions tab to view the unit test workflow (I'll make a dummy PR after this is merged to test it
- https://trello.com/c/G6DVclL0/107-add-github-action-to-run-tests
Created a dummy pr on my fork to test it:

Unit test Github Action

---

src/components/backNavigation/BackNavigation.test.js
src/components/profileDetails/PersonProfile.test.js
src/components/tabs/Tabs.js
src/components/tabs/Tabs.test.js

- Adds unit tests for BackNavigation, PersonProfile, and Tabs
- Complete unit testing in the codebase
- `yarn test`
- https://trello.com/c/WSHTMjJU/94-initial-unit-tests

Chore: Unit tests for BackNavigation, PersonProfile, and Tabs

---

README.md
public/index.html
src/components/about/About.js
src/components/footer/Footer.js
src/pages/DonationDetail.js
src/pages/PetitionDetail.js
src/pages/ProfileDetail.js

Tweak copy for About page and mission statement.
Remove lines of copy relating to law enforcement.
Run yarn start
https://trello.com/c/9V49VELM/112-tweak-about-page-and-mission-statement-copy

chore: remove 'at the hands of law enforcement.'

---

src/components/footer/Footer.js

-Change black queens and kings to 'black royalty' so our language is more inclusive to black non-binary people
-
-Navigate to footer
-

update footer description.

---

.prettierrc
src/components/pagination/Pagination.test.js
src/components/ui/actionDetailsContent/ActionDetailsContent.test.js
src/components/ui/actionDetailsHeader/ActionDetailsHeader.test.js
src/components/ui/getInvolved/GetInvolved.test.js
src/components/ui/hashtags/HashTags.test.js
src/components/ui/news/News.test.js
src/components/ui/newsList/NewsList.test.js
src/components/ui/petition/Petition.test.js
src/components/ui/profileList/ProfileList.test.js
src/components/ui/profilePreview/ProfilePreview.test.js
src/components/ui/share/Share.test.js

- Add unit tests for all UI components
- Adds prettier rule for trailing commas to match eslint rule
- Add unit tests for all UI components
- `yarn test`
- https://trello.com/c/WSHTMjJU/94-initial-unit-tests

Chore: UI component unit tests and trailing comma prettier rule

---

public/index.html
src/components/profileDetails/PersonProfile.js
src/components/ui/hashtags/style.js
src/pages/ProfileDetail.js

- Make API changes
- Add API changes
- Visit the ProfileDetail page
- https://trello.com/c/NtVoDDs4/116-fix-new-object-modified-from-backend

Make api changes

---

.huskyrc.json
package.json
public/index.html
src/App.js
src/components/common/Seo.js
src/index.js
yarn.lock

- Meta tag fix
- Fix meta tags
- Test on [metatags](metatags.io)
- https://trello.com/c/8F2e0JLt/118-fix-meta-tags

Meta tag fix

---

src/pages/Petitions.js

-Added  missing "the" on the petition description page
-
-
-

 missing "the" on petition description page

---

src/components/about/About.js

-About page copy changes
-
-
-

Update about -page

---

src/components/ui/profileList/ProfileList.js
src/pages/AboutPage.test.js
src/pages/DonationDetail.js
src/pages/DonationDetail.test.js
src/pages/notFound/NotFound.test.js

- Unit tests for pages AboutPage, DonationDetail, and NotFound page
- Unit tests for pages AboutPage, DonationDetail, and NotFound page
- Switching error for DonationDetail page
- `yarn test`
- throw an error after `axios.get` and the page won't fail gracefully.
- https://trello.com/c/WSHTMjJU/94-initial-unit-tests

Chore: Unit test AboutPage, DonationDetail, and NotFound page

---

.eslintrc
package.json
src/components/privacyPolicy/PrivacyPolicy.test.js
src/components/termsOfService/TermsOfService.test.js
yarn.lock

- Add `test:coverage` script
- Add unit tests for PrivacyPolicy and TermsOfService
- Fixes prettier and eslint conflicts
- Add `test:coverage` script
- Add unit tests for PrivacyPolicy and TermsOfService
- `yarn test`
- https://trello.com/c/mic1cMtx/120-second-round-of-unit-tests

Chore: Coverage script and tests for Privacy and Terms

---

src/pages/Donations.js
src/pages/Donations.test.js

- Fix the unit tests for Donations https://github.com/Say-Their-Name/say-their-names-web/issues/129
- Fixed unit tests for Donations
- `yarn test`
- https://trello.com/c/WSHTMjJU/94-initial-unit-tests

Bug: Donations tests

---

src/components/ui/actionDetailsHeader/ActionDetailsHeader.test.js
src/pages/Petitions.test.js

- Fixing errors for Petition and ActionDetailsHeader
- Fixing errors for Petition and ActionDetailsHeader
- `yarn test`
- N/A

Bug: errors in Petition and ActionDetailsHeader

---

src/components/pagination/styles.js
src/components/profileDetails/styles.js
src/components/tabs/styles.js
src/components/ui/share/styles.js

- Enhance keyboard navigation.
- Make pagination, tabs, and share to social buttons keyboard navigable. To do this it also changes Tabs from links to buttons. 
- Open `deploy preview`
- https://trello.com/c/aSnrip5u/110-a11y-enhancements

Keyboard navigation accessibility enhancement

---

.env.example
src/components/footer/Footer.js
src/components/footer/Footer.test.js
src/components/footer/style.js

- Remove Downloads from Footer
- Comment out download section on the footer, pending the time the mobile links are ready
- Checkout the footer
-

Remove Downloads from Footer

---

src/components/footer/style.js

- Change color on footer
- Change color on footer
-
-

Change color on footer

---

src/components/footer/Footer.js
src/constants/Variables.js

Adds IOS link to footer
Add IOS link to footer
Load `deploy preview`

added ios link

---

src/components/footer/Footer.js
src/components/footer/style.js
src/constants/Variables.js

- Add IOS Link to footer
- Add IOS Link to footer
- Check the footer of the app
-

Add IOS Link to footer

---

.github/workflows/unit-test.yaml

- Fix .unit-test.yaml
- Visit a profile detail page
-

Fix .unit-test.yaml
